import theme from '@/theme';
import { Box, Container, CssBaseline, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { SystemStyleObject } from '@mui/system';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AppRouterCacheProvider>
					<CssBaseline />

					<ThemeProvider theme={theme}>
						<Box sx={background}>
							<Box component="main" sx={content}>
								<Container>{children}</Container>
							</Box>
						</Box>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
};

const inter = Inter({ subsets: ['latin'] });

const background: SystemStyleObject = {
	minHeight: '100vh',
	background:
		'linear-gradient(180deg, rgba(0,8,14,1) 0%, rgba(20,42,80,1) 100%)',
};

const content: SystemStyleObject = {
	px: 1,
	py: 3,
};

export default RootLayout;
